### PR TITLE
Added helper functions to help finding a target to attack 

### PR DESCRIPTION
**Pull request by elnappo**

### CODE REVIEW

**Comment by elnappo** [comment]
Will update PR tomorrow to use `AttackableValue()` in `HasShipDefenses()`.

**Comment by alaingilbert** [comment]
Awesome, I was looking at the code. I really like it :D

**Comment by elnappo** [comment]
Done, this way it's much shorter.

**Comment by jc01rho** [comment]
very nice codes :)

**Review by alaingilbert — APPROVED** [review]

**Comment by alaingilbert** [comment]
Remake your PR against "develop" branch please

**Pull request merged**
