### PR TITLE
Fix malfunction of GetStaticHandler

### PR DESCRIPTION
**Pull request by 0xE232FE**
By adding only selected header fields from the origin response.

I do not know if this header fields needed at all.

### CODE REVIEW

**Comment by 0xE232FE** [comment]
Fixed another issue on the Marketpage where Sort, Filter and Page Navigation isn't working propably, because of the javascript that can not load corresponding javascripts.

**Comment by alaingilbert** [comment]
I don't get the headers part changes.

**Comment by 0xE232FE** [comment]
> 
> 
> I don't get the headers part changes.
> The marketplace paging seems to work without the headers changes.

Yes, you are right the Marketplaces is not affected by the headers changes!!! This are two different problems.

**Comment by flashover** [comment]
> And the Function GetStaticHEADHandler handles the Headers is this also needed in the GetStaticHandler at all? Because GetStaticHandler works even when I delete the whole copy header thing.

As I said, I don't know 100% sure anymore why I copied the headers back to the client. I thought it was for Caching + Content-Type and also Age (is it "max-age"? I don't know the correct name anymore).

The `Function GetStaticHEADHandler` is there for AntiGameReborn. It checks with HTTP-HEAD if the Age-related header has expired and if so then the AGR follows up with a HTTP-GET (=GetStaticHandler) and pulls the updates XML files from `/api/` on the origin server. So I would not want to remove the copy-headers from `GetStaticHandler` because potentially we write wrong Age-related header for AntiGameReborn caching of XML files.

**Comment by alaingilbert** [comment]
@0xE232FE Everything works fine for me without the header changes (L927-L929).
Remove this and I'll merge.
Also rename `doubleescapedServerURL` -> `doubleEscapedServerURL`.
Thanks.

**Comment by 0xE232FE** [comment]
Okay I **removed** the Header thing for you in my pull requesst!

For me it is not working propably with the all headers copied in the GetStaticHandler.
I am very surprised that this is working for you guys!

**Comment by flashover** [comment]
Could it be because I'm using a full FQDN and you're using host 127.0.0.1:8080 ?

**Comment by alaingilbert** [comment]
How can I reproduce what is not working for you ?

**Comment by 0xE232FE** [comment]
> Could it be because I'm using a full FQDN and you're using host 127.0.0.1:8080 ?

I tried FQDN and it doesn't make a difference, check my screenshot.

To reproduce the Header Problems just try to get a simple JScript file for example:
ogamed: http://127.0.0.1:8080/cdn/js/skins/default/resourcesbar.js
direct website: https://s165-de.ogame.gameforge.com/cdn/js/skins/default/resourcesbar.js

grafik

**Pull request merged**
